name: Nightly build to test
on:
  push:
    branches:
      - 'main'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.MYNA_APP_ID }}
          private-key: ${{ secrets.MYNA_APP_SECRET }}
      - name: 'bot: version bump'
        uses: phips28/gh-action-bump-version@master
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
        with:
          version-type: 'prerelease'
          commit-message: 'bump version'
          skip-tag: 'true'
          skip-commit: 'false'
      - name: Build project
        run: |
          npm install
          npm run build
          mkdir -p tmp/recorder
          rsync -ar dist package.json config_sample.yaml tmp/recorder/
          cd tmp
          zip -X -r recorder.zip recorder
      - name: Upload by ftp
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.PNM_FTP_HOST }}
          username: ${{ secrets.PNM_FTP_USER }}
          password: ${{ secrets.PNM_FTP_PASSWORD }}
          local-dir: "./tmp/"
          state-name: ".recorder-sync-state.json"
          exclude: |
            **/recorder/**
