name: Build and release recorder
on:
  push:
    tags:
      - 'v*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9
      - name: Build project
        run: |
          pnpm install
          pnpm run build
          mkdir -p tmp/recorder
          rsync -ar dist package.json config_sample.yaml tmp/recorder/
          cd tmp
          zip -X -r recorder.zip recorder
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: upload recorder
          path: tmp/recorder.zip
      - name: Upload to release
        uses: JasonEtco/upload-to-release@master
        with:
          args: tmp/recorder.zip application/zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
