name: Build and release recorder
on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: node
      - name: Checkout
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/checkout@v4
      - name: setup node
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - uses: pnpm/action-setup@v4
        if: ${{ steps.release.outputs.release_created }}
        name: Install pnpm
        with:
          version: 9
      - name: Build project
        if: ${{ steps.release.outputs.release_created }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pnpm install
          pnpm run build
          mkdir -p tmp/recorder
          rsync -ar dist package.json config_sample.yaml tmp/recorder/
          cd tmp
          zip -X -r recorder.zip recorder
          gh release upload ${{ steps.release.outputs.tag_name }} recorder.zip
